### ISSUE TITLE
some times the composer commond not in /usr/bin

### ISSUE THREAD

**Issue by justmd5** [cybercog/laravel-paket#74]
some times the composer commond not in

```/usr/bin```

,such as. in mac or other linux os dont have permission to write，so often we put the composer in 

```/usr/local/bin ```

consider removing the definition of path and switching to the definition of environment path or any other better choice ?

**Comment by antonkomarev** [comment]
We might add configurable value and pass it to the Composer class on instantiation in the `PaketServiceProvider`.

**Comment by justmd5** [comment]
commit a pr,please review,tks!

**Comment by antonkomarev** [comment]
[Laravel Paket v1.8.0](https://github.com/cybercog/laravel-paket/releases/tag/1.8.0) has been released.
