### ISSUE TITLE
php8 support

### ISSUE THREAD

**Issue by afrizal423** [cybercog/laravel-paket#83]
does your package not support php 8?
```
[InvalidArgumentException]
  Package cybercog/laravel-paket has a PHP requirement incompatible with your PHP version, PHP extensions and Compose
  r version
```

**Comment by antonkomarev** [comment]
Yes, seems so. Add it to composer.json, please

**Comment by afrizal423** [comment]
So, am I forks first and then pull requests?

**Comment by antonkomarev** [comment]
Merged, thanks @afrizal423! Cannot make a release from mobile phone. Will do it as soon as I will get to my laptop.

**Comment by antonkomarev** [comment]
Sorry for the long delay, [Laravel Paket v1.9.0](https://github.com/cybercog/laravel-paket/releases/tag/1.9.0) has been released with PHP 8 support! Thanks @afrizal423!
